Repository hack4impact-uiuc/bridge, pull requests merged in 2020-05, with the labels that each got.

#34 Create <Text /> Component
  CONTRIBUTING.md
  README.md
  playground/Playground.js
  src/__tests__/Text.js
  src/__tests__/__snapshots__/Button.js.snap
  src/__tests__/__snapshots__/Link.js.snap
  src/__tests__/__snapshots__/Text.js.snap
  src/components/Button/Button.js
  src/components/Link/Link.js
  src/components/Text/Text.js
  src/components/Text/index.js
  src/components/index.js
  src/theme.js
  src/utils/constants.js
Labels: component

#35 Explicitly state "as" PropType for Text
  src/components/Text/Text.js
Labels: component

#39 Bump version to 0.0.3
  README.md
  package.json
Labels: component

#40 Create <Tag> Component
  src/__tests__/Tag.js
  src/__tests__/__snapshots__/Tag.js.snap
  src/components/Tag/Tag.js
  src/components/Tag/index.js
  src/components/index.js
Labels: component

#48 Resolves #29 match colors, spacing, typography to design system
  src/__tests__/Link.js
  src/__tests__/Text.js
  src/__tests__/__snapshots__/Card.js.snap
  src/__tests__/__snapshots__/Tag.js.snap
  src/__tests__/__snapshots__/Text.js.snap
  src/components/Tag/Tag.js
  src/components/Text/Text.js
  src/theme.js
Labels: bug, component

#49 Add Flex props to Box to allow it to be used as a flex item + bump to 0.0.4
  package.json
  src/__tests__/Box.js
  src/__tests__/__snapshots__/Box.js.snap
  src/components/Box/Box.js
  src/components/Flex/Flex.js
Labels: component

#50 Resolves #23 Add <Icons />
  playground/Playground.js
  src/__tests__/Icon.js
  src/__tests__/__snapshots__/Icon.js.snap
  src/components/Icon/Icon.js
  src/components/Icon/IconPaths.js
  src/components/Icon/index.js
  src/components/index.js
Labels: component

#57 Documentation Main Page + Example Documentation + Syntax Highlighting
  docs/.babelrc
  docs/components/CodeBlock.js
  docs/components/layout.js
  docs/components/markdown.js
  docs/components/mdx-components.js
  docs/package.json
  docs/pages/_document.js
  docs/pages/components/buttons.mdx
  docs/pages/components/common-props.mdx
  docs/pages/components/links.mdx
  docs/pages/index.js
  docs/public/icons/do-icon.svg
  docs/public/icons/dont-icon.svg
  docs/public/temp1.png
  docs/public/temp2.png
  docs/yarn.lock
Labels: website

#60 Add <Textfield /> Component
  docs/lib/data/components.js
  docs/pages/components/text-field.mdx
  playground/Playground.js
  src/__tests__/TextField.js
  src/__tests__/__snapshots__/Button.js.snap
  src/__tests__/__snapshots__/Card.js.snap
  src/__tests__/__snapshots__/TextField.js.snap
  src/components/Button/Button.js
  src/components/Card/Card.js
  src/components/TextField/TextField.js
  src/components/TextField/index.js
  src/components/index.js
  src/theme.js
Labels: component

#62 fix bug where button size gets bigger because of outline
  src/__tests__/__snapshots__/Button.js.snap
  src/__tests__/__snapshots__/Card.js.snap
  src/components/Button/Button.js
  src/theme.js
Labels: bug, component

#63 Resolves #61 Add documentation on how to add new doc
  docs/README.md
Labels: documentation, website

#68 added button.group + added colors to COMMON + added pointer:cursor
  CONTRIBUTING.md
  docs/lib/data/components.js
  docs/pages/components/buttons.mdx
  docs/pages/components/common-props.mdx
  docs/pages/components/heading.mdx
  docs/pages/components/text-field.mdx
  docs/pages/components/text.mdx
  docs/pages/components/theming.mdx
  src/__tests__/Alert.js
  src/__tests__/Button.js
  src/__tests__/Card.js
  src/__tests__/Tag.js
  src/__tests__/__snapshots__/Box.js.snap
  src/__tests__/__snapshots__/Button.js.snap
  src/__tests__/__snapshots__/Card.js.snap
  src/components/Alert/Alert.js
  src/components/Box/Box.js
  src/components/Button/Button.js
  src/components/Button/ButtonGroup.js
  src/components/Card/Card.js
  src/components/Link/Link.js
  src/components/Tag/Tag.js
  src/components/index.js
  src/utils/constants.js
Labels: component

#69 More Design Documentation
  docs/README.md
  docs/components/col.js
  docs/components/design/colorPalette.js
  docs/components/design/do-dont.js
  docs/components/layout.js
  docs/components/mdx-components.js
  docs/components/row.js
  docs/components/sidebar.js
  docs/lib/constants.js
  docs/lib/data/design.js
  docs/lib/data/designs.js
  docs/package.json
  docs/pages/components/buttons.mdx
  docs/pages/components/heading.mdx
  docs/pages/components/icons.mdx
  docs/pages/components/links.mdx
  docs/pages/components/tags.mdx
  docs/pages/components/text.mdx
  docs/pages/design/alerts.mdx
  docs/pages/design/buttons.mdx
  docs/pages/design/colors.mdx
  docs/pages/design/index.js
  docs/pages/design/typography.mdx
  docs/public/docs-content/design/colors/color-do.png
  docs/public/docs-content/design/colors/color-dont.png
  docs/yarn.lock
Labels: website

#70 <Alert /> should fit parent
  src/__tests__/__snapshots__/Alert.js.snap
  src/components/Alert/Alert.js
Labels: component

#75 Resolves #73 #43 Home Page and navbar
  docs/components/home/navbar.js
  docs/components/layout.js
  docs/components/sidebar.js
  docs/pages/_document.js
  docs/pages/about.mdx
  docs/pages/index.js
  docs/public/homepage/bridge-web-landing.svg
  docs/public/homepage/components.svg
  docs/public/homepage/design.svg
  docs/public/homepage/github-logo.png
  docs/public/homepage/menu.svg
  docs/public/homepage/white_h4i_logo.png
Labels: website

#77 More documentation
  docs/components/CodeExampleBox.js
  docs/components/home/navbar.js
  docs/components/layout.js
  docs/components/mdx-components.js
  docs/lib/data/components.js
  docs/pages/about.mdx
  docs/pages/components/alerts.mdx
  docs/pages/components/box.mdx
  docs/pages/components/buttons.mdx
  docs/pages/components/cards.mdx
  docs/pages/components/common-props.mdx
  docs/pages/components/flex.mdx
  docs/pages/components/grid.mdx
  docs/pages/components/icons.mdx
  docs/pages/components/index.js
  docs/pages/components/index.mdx
  docs/pages/components/responsive.mdx
  docs/pages/components/tags.mdx
  docs/pages/design/colors.mdx
  docs/pages/design/index.js
  docs/pages/design/index.mdx
Labels: documentation, website

#76 Add <Radio /> Component
  docs/lib/data/components.js
  docs/pages/components/radio.mdx
  docs/pages/components/text-field.mdx
  src/__tests__/Radio.js
  src/__tests__/__snapshots__/Radio.js.snap
  src/__tests__/__snapshots__/TextField.js.snap
  src/components/Radio/Radio.js
  src/components/Radio/RadioGroup.js
  src/components/Radio/index.js
  src/components/TextField/TextField.js
  src/components/index.js
  src/theme.js
Labels: component

#81 Live CodeBlock + more documentation
  docs/README.md
  docs/components/CodeBlock.js
  docs/components/CodeExampleBox.js
  docs/components/mdx-components.js
  docs/package.json
  docs/pages/components/alerts.mdx
  docs/pages/components/box.mdx
  docs/pages/components/buttons.mdx
  docs/pages/components/cards.mdx
  docs/pages/components/common-props.mdx
  docs/pages/components/flex.mdx
  docs/pages/components/grid.mdx
  docs/pages/components/heading.mdx
  docs/pages/components/icons.mdx
  docs/pages/components/links.mdx
  docs/pages/components/tables.mdx
  docs/pages/components/tags.mdx
  docs/pages/components/text-field.mdx
  docs/pages/components/text.mdx
  docs/yarn.lock
Labels: website

#84 Add more design guidelines. Alert and spacing documentation. Alert stuff
  docs/lib/data/design.js
  docs/pages/design/alerts.mdx
  docs/pages/design/breakpoints.mdx
  docs/pages/design/cards.mdx
  docs/pages/design/forms.mdx
  docs/pages/design/logos.mdx
  docs/pages/design/spacing.mdx
  docs/pages/design/tables.mdx
  docs/pages/design/tags.mdx
  src/__tests__/__snapshots__/Alert.js.snap
  src/components/Alert/Alert.js
Labels: website

#82 Table font, Card default size, grey vs gray fixes
  docs/components/design/colorPalette.js
  playground/Playground.js
  src/__tests__/Table.js
  src/__tests__/__snapshots__/Card.js.snap
  src/__tests__/__snapshots__/Table.js.snap
  src/components/Card/Card.js
  src/components/Table/Table.js
  src/components/Table/TableBody.js
  src/components/Table/TableCell.js
  src/components/Table/TableHead.js
  src/components/Table/TableRow.js
  src/theme.js
Labels: component

#86 more design docs + static build
  docs/.babelrc
  docs/components/regular-layout.js
  docs/package.json
  docs/pages/about.mdx
  docs/pages/design/breakpoints.mdx
  docs/pages/design/index.mdx
  docs/pages/design/logos.mdx
  docs/pages/design/typography.mdx
  docs/public/bridge-banner.png
  docs/public/h4i-logos/h4i-colored-logo.png
  docs/public/h4i-logos/h4i-colored-square.png
  docs/public/h4i-logos/h4i-white-logo.png
  docs/public/h4i-logos/h4i-white-square.png
Labels: website

#90 Resolve #87 update tag font styling
  src/__tests__/Tag.js
  src/__tests__/__snapshots__/Tag.js.snap
  src/components/Radio/Radio.js
  src/components/TextField/TextField.js
Labels: component
